
# restore_model: ''
restore_model: ./pretrained/tacotron2_ar_adv.pth
# restore_model: ./checkpoints/exp_tc2/states.pth

log_dir: logs/exp_tc2
checkpoint_dir: checkpoints/exp_tc2

# dataset
train_wavs_path: G:/data/arabic-speech-corpus/wav_new
train_labels: ./data/train_phon.txt

test_wavs_path: G:/data/arabic-speech-corpus/test set/wav_new
test_labels: ./data/test_phon.txt

label_pattern: '"(?P<filename>.*)" "(?P<phonemes>.*)"'
# label_pattern: (?P<arabic>.*)\|(?P<filestem>.*)

# optimizers
g_lr: 1.0e-3    # lr for AdamW optimizer (generator)
g_beta1: 0.9     # beta1 for AdamW optimizer (generator)
g_beta2: 0.999   # beta2 for AdamW optimizer (generator)

n_save_states_iter: 10
n_save_backup_iter: 1000
